{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.0.0.jar",
          "url": "manifest-merger-31.0.0.jar",
          "size": 224062,
          "sha512": "f25f4ff239001da08ad2ee4fb77c3bc535d5e072fb032d4647e74c21866a3efda36122e5ef042af8fb87fdcd29baab582e0d56c2751ecaa48f7edddba86a13c0",
          "sha256": "e1feb9f8c9b98dfa6eb073f068588d268a946d3c86e4dcf8bfd1a957891f2db6",
          "sha1": "115f4fe77f18921e983c82c48b820949a4123d8e",
          "md5": "53e86a872389eadc9d53cd4d7da8e316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.0.0.jar",
          "url": "manifest-merger-31.0.0.jar",
          "size": 224062,
          "sha512": "f25f4ff239001da08ad2ee4fb77c3bc535d5e072fb032d4647e74c21866a3efda36122e5ef042af8fb87fdcd29baab582e0d56c2751ecaa48f7edddba86a13c0",
          "sha256": "e1feb9f8c9b98dfa6eb073f068588d268a946d3c86e4dcf8bfd1a957891f2db6",
          "sha1": "115f4fe77f18921e983c82c48b820949a4123d8e",
          "md5": "53e86a872389eadc9d53cd4d7da8e316"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.0.0-javadoc.jar",
          "url": "manifest-merger-31.0.0-javadoc.jar",
          "size": 265238,
          "sha512": "60ce529baa8d2af785eb9539414b434702b0e6b695bbde668f97096ccf6b54f16717005d8cba0ef7deef9c318b3dadd1e152bc3726547b2eb23e59d3a2ba0ec8",
          "sha256": "19fa8e0fff16322f9c077c318586e52a53b64cc0c2d250c4c349b0ca1ba98f78",
          "sha1": "f05372664761d024bbd7c7c42a09057d5d5b6016",
          "md5": "575d9fa4b5e062c80ed4e0b5c25a473c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.0.0-sources.jar",
          "url": "manifest-merger-31.0.0-sources.jar",
          "size": 215061,
          "sha512": "94ad458d6d31db20e99a6210d3bb60716c0739da82c1134c9714161cd0bf1cf52d0b1d27902a069fe29741fa4689313f2ca66c4c9b8dcda173e36b6760f1b0eb",
          "sha256": "2921e8231d73e118a55cf50a5d4d440c7c4760458d8dd9146575e356b947ff4a",
          "sha1": "6b704b4f18893b0bdd5a14d140b1b0b4ddfaabe4",
          "md5": "8cdef36c9585d1e80d3497ab7a8a2b22"
        }
      ]
    }
  ]
}
