{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.0.0.jar",
          "url": "gradle-api-8.0.0.jar",
          "size": 269943,
          "sha512": "f35758fcc7dd581f3275ec3ef3ea11941853aec318a945a0e788a3c6f1cab7bc3c2ebb029f713909feab45bbe570eeca51d2ee8a93abc38c1fc6f05546f41d43",
          "sha256": "3179f8ea0fceba7d19f6f99518bcd78a331c70370674b7dd671e456e43645778",
          "sha1": "6b219420bfa0ed1c10496c3d77e2a6eb445a3608",
          "md5": "b4301cacef87db93dc9aebe16f80606f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.0.0.jar",
          "url": "gradle-api-8.0.0.jar",
          "size": 269943,
          "sha512": "f35758fcc7dd581f3275ec3ef3ea11941853aec318a945a0e788a3c6f1cab7bc3c2ebb029f713909feab45bbe570eeca51d2ee8a93abc38c1fc6f05546f41d43",
          "sha256": "3179f8ea0fceba7d19f6f99518bcd78a331c70370674b7dd671e456e43645778",
          "sha1": "6b219420bfa0ed1c10496c3d77e2a6eb445a3608",
          "md5": "b4301cacef87db93dc9aebe16f80606f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.0.0-javadoc.jar",
          "url": "gradle-api-8.0.0-javadoc.jar",
          "size": 150993,
          "sha512": "8c6bb2f58ca411722df3c7cd1ab8b4c0b5355ef25b294d51e835211ed8afe0aa8470db2e0d045147fa8a52dde520e6a5b645975bf58c856a2229ff6b75c76bc1",
          "sha256": "9b830c1e09ca8447a4958a16ff59d07bf7b104c2419e26a9eaa13d139234e63c",
          "sha1": "8b2f3d3ee358154cfb83c38cc7fea8b87fa1e91a",
          "md5": "a190dd692939af482e86d62185d6d208"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.0.0-sources.jar",
          "url": "gradle-api-8.0.0-sources.jar",
          "size": 265161,
          "sha512": "1ea7bf2c1f13226f043bfb25a8ab96f2d8d7798ab3be41b97a11b07c645169fcabcd06c125330567e81e1cbcdc46840d440e9214b249087a7d3fb24431ba2fe2",
          "sha256": "67414701840d8efdc327c63c1af3fc61988f4332717ebe6e9f0c9652e1fa1ae3",
          "sha1": "86d672c39cf78294c62b685bdc31a4e24b465ce0",
          "md5": "72e2336ea000de8584fb51363aba7343"
        }
      ]
    }
  ]
}
