{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.0.0.jar",
          "url": "builder-8.0.0.jar",
          "size": 11283330,
          "sha512": "352e2ee116be9ca33e3c750d212453b80c103e9e99206a521f58340193103e41fef56cabdf58f84defb2c20ad27117e6caa96b0d19d3945b9f89f78ec0896b99",
          "sha256": "d892991279f1cc14b1cdf29ea9f688354608ce52e6269a1e87a345f1d6b0feb6",
          "sha1": "201e508c3edbbf524e8e8985b78bd49d9c3b6b77",
          "md5": "ad6b1eda966aed351edec6a92b82d7b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.0.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.0.0.jar",
          "url": "builder-8.0.0.jar",
          "size": 11283330,
          "sha512": "352e2ee116be9ca33e3c750d212453b80c103e9e99206a521f58340193103e41fef56cabdf58f84defb2c20ad27117e6caa96b0d19d3945b9f89f78ec0896b99",
          "sha256": "d892991279f1cc14b1cdf29ea9f688354608ce52e6269a1e87a345f1d6b0feb6",
          "sha1": "201e508c3edbbf524e8e8985b78bd49d9c3b6b77",
          "md5": "ad6b1eda966aed351edec6a92b82d7b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.0.0-javadoc.jar",
          "url": "builder-8.0.0-javadoc.jar",
          "size": 400519,
          "sha512": "30849e0d1ed21c101febf4462f8de6ab615675e921a2f31bdcf359bef212e0abb193ebc97b3ebb08269629235dcf6f9536163c4e53392171218357dc55a8899b",
          "sha256": "d2c576fd4b7d0c6810877928e55ebbb5f56889af289299a1aebfa0b87bcb467e",
          "sha1": "7af55a09479c649512da50053db92fa2cb05f23b",
          "md5": "6a6b32b9af8919ecbd3808987c7fce93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.0.0-sources.jar",
          "url": "builder-8.0.0-sources.jar",
          "size": 281867,
          "sha512": "51bf84745129c519232210aca2ae54e10899c9d92e2c7526fb0de7f6047132f007259986416205cabcfc9e3930d5baea2e3a95e87ce5520e0a0cc3ee481a6b2b",
          "sha256": "0395ec921a3bad1dfdd520a7d936ec3b6be03add1755c03047616764353badc2",
          "sha1": "bb0a3fbbb16410e745eacafc4f9a8a422c2ca225",
          "md5": "f446faaff70edd0071eba724e41de6bc"
        }
      ]
    }
  ]
}
