{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.6.1.aar",
          "url": "webkit-1.6.1.aar",
          "size": 136457,
          "sha512": "9064190ab46ca1fa05ccbb4605b3bc03ebf360d89771cfbf738cacd52c713ed24e34c249f27ff586c2e1d9e07249d4e4175218210f165f19c5b5396f85da0a7b",
          "sha256": "a255d265ff6249ab7b6f26efdf2c36aaff80ceaffcd10d496a87ae927c2350ea",
          "sha1": "a5f210998362a40d567beaf93dc5f2ea51ffbc86",
          "md5": "545b94dc6863416a41b09d74f187ec0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.6.1.aar",
          "url": "webkit-1.6.1.aar",
          "size": 136457,
          "sha512": "9064190ab46ca1fa05ccbb4605b3bc03ebf360d89771cfbf738cacd52c713ed24e34c249f27ff586c2e1d9e07249d4e4175218210f165f19c5b5396f85da0a7b",
          "sha256": "a255d265ff6249ab7b6f26efdf2c36aaff80ceaffcd10d496a87ae927c2350ea",
          "sha1": "a5f210998362a40d567beaf93dc5f2ea51ffbc86",
          "md5": "545b94dc6863416a41b09d74f187ec0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.6.1-sources.jar",
          "url": "webkit-1.6.1-sources.jar",
          "size": 154250,
          "sha512": "ce98ef20ec6af203a3bf27cee624e18026af96e0892e38ace1686df6a7fcd6952ca986a0c3e80f2f0a53c59d783fa2dae1c617bc99eef2bdb0c5b743c7f858ae",
          "sha256": "dd0e904cfe39acc7c227ec07f0443a65a0aff740f8495f8021dea51621d85138",
          "sha1": "4745f634df12a385bf4ab5126834f91eaef57d5a",
          "md5": "12814434156d45e5eb48c8126b82527f"
        }
      ]
    }
  ]
}