{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-splashscreen",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0.aar",
          "url": "core-splashscreen-1.0.0.aar",
          "size": 35230,
          "sha512": "cb3dc9318bcd34c2bc16b411a35c4dae18c3486cdfeeaf8dd148bbe7f7f73d5bf42687f56e5b5ec0d41c4bf5279ad407e4749a966dacf49649771600873f572d",
          "sha256": "3e86b23dc1ca3fc4abc211ee9ca7c889f478743e2482458a6267e6023dcf2a72",
          "sha1": "6b1eccca966811faafb13f6c2f88351504dc9eae",
          "md5": "75d50d1a146d331834fc3f5cee6492ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0.aar",
          "url": "core-splashscreen-1.0.0.aar",
          "size": 35230,
          "sha512": "cb3dc9318bcd34c2bc16b411a35c4dae18c3486cdfeeaf8dd148bbe7f7f73d5bf42687f56e5b5ec0d41c4bf5279ad407e4749a966dacf49649771600873f572d",
          "sha256": "3e86b23dc1ca3fc4abc211ee9ca7c889f478743e2482458a6267e6023dcf2a72",
          "sha1": "6b1eccca966811faafb13f6c2f88351504dc9eae",
          "md5": "75d50d1a146d331834fc3f5cee6492ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-splashscreen-1.0.0-sources.jar",
          "url": "core-splashscreen-1.0.0-sources.jar",
          "size": 11458,
          "sha512": "758509ae4c596c8e9262c0bc930bf186b98778dc0a50f575e2e124920eaae5c4f38e66aaf79198cc3ef2021e7f9cc1bf2cb20227e8c9d8e9cdf46efcc9e7a576",
          "sha256": "f8c16e2b159971feed61d4c12b0fbf53da91f99f855cb893e5a8f2b67772907f",
          "sha1": "e033216357e9111d8d520996527bbd098bd81a66",
          "md5": "f0dddaf82ac1dc7148f9a97fe7919ad6"
        }
      ]
    }
  ]
}